require "embeds/companionInfo"
require "embeds/help"
require "embeds/lobbiesInfo"
require "embeds/matchmakingInfo"
require "embeds/serverInfo"
require "embeds/ok"
require "embeds/warning"
require "embeds/error"