---@enum (key) textLine
local text = {

	-- help
	helpSelectorPlaceholder = true,
	helpSelectorLobby = true,
	helpSelectorLobbyMore = true,
	helpSelectorMatchmaking = true,
	helpSelectorCompanion = true,
	helpSelectorRoom = true,
	helpSelectorServer = true,
	helpSelectorOther = true,

	helpContentsLobby = true,
	helpContentsSLobby = true,
	helpContentsMatchmaking = true,
	helpContentsSMatchmaking = true,
	helpContentsCompanion = true,
	helpContentsSCompanion = true,
	helpContentsRoom = true,
	helpContentsSRoom = true,
	helpContentsServer = true,
	helpContentsSServer = true,
	helpContentsOther = true,
	helpContentsSOther = true,

	helpLobbyHeader = true,
	helpLobbySetup = true,
	helpLobbySSetup = true,
	helpLobbyView = true,
	helpLobbySView = true,
	helpLobbyAdd = true,
	helpLobbySAdd = true,
	helpLobbyRemove = true,
	helpLobbySRemove = true,
	helpLobbyCategory = true,
	helpLobbySCategory = true,
	helpLobbyCapacity = true,
	helpLobbySCapacity = true,
	helpLobbyLimit = true,
	helpLobbySLimit = true,
	helpLobbyBitrate = true,
	helpLobbySBitrate = true,

	helpLobbyName = true,
	helpLobbySName = true,
	helpLobbyPermissions = true,
	helpLobbySPermissions = true,
	helpLobbyRole = true,
	helpLobbySRole = true,

	helpMatchmakingHeader = true,
	helpMatchmakingSetup = true,
	helpMatchmakingSSetup = true,
	helpMatchmakingView = true,
	helpMatchmakingSView = true,
	helpMatchmakingAdd = true,
	helpMatchmakingSAdd = true,
	helpMatchmakingRemove = true,
	helpMatchmakingSRemove = true,
	helpMatchmakingTarget = true,
	helpMatchmakingSTarget = true,
	helpMatchmakingMode = true,
	helpMatchmakingSMode = true,

	helpCompanionHeader = true,
	helpCompanionSetup = true,
	helpCompanionSSetup = true,
	helpCompanionView = true,
	helpCompanionSView = true,
	helpCompanionEnable = true,
	helpCompanionSEnable = true,
	helpCompanionDisable = true,
	helpCompanionSDisable = true,
	helpCompanionCategory = true,
	helpCompanionSCategory = true,
	helpCompanionName = true,
	helpCompanionSName = true,
	helpCompanionGreeting = true,
	helpCompanionSGreeting = true,
	helpCompanionLog = true,
	helpCompanionSLog = true,

	helpRoomHeader = true,
	helpRoomView = true,
	helpRoomSView = true,
	helpRoomHost = true,
	helpRoomSHost = true,
	helpRoomInvite = true,
	helpRoomSInvite = true,
	helpRoomKick = true,
	helpRoomSKick = true,
	helpRoomMute = true,
	helpRoomSMute = true,
	helpRoomBlock = true,
	helpRoomSBlock = true,
	helpRoomHide = true,
	helpRoomSHide = true,
	helpRoomLock = true,
	helpRoomSLock = true,
	helpRoomPassword = true,
	helpRoomSPassword = true,
	helpRoomRename = true,
	helpRoomSRename = true,
	helpRoomResize = true,
	helpRoomSResize = true,
	helpRoomBitrate = true,
	helpRoomSBitrate = true,

	helpServerHeader = true,
	helpServerSetup = true,
	helpServerSSetup = true,
	helpServerView = true,
	helpServerSView = true,
	helpServerLimit = true,
	helpServerSLimit = true,
	helpServerPermissions = true,
	helpServerSPermissions = true,
	helpServerRole = true,

	helpHelp = true,
	helpSHelp = true,
	helpSupport = true,
	helpSSuport = true,
	helpReset = true,
	helpSReset = true,
	helpClone = true,
	helpSClone = true,
	helpDelete = true,
	helpSDelete = true,
	helpUsersPrint = true,
	helpUsersSPrint = true,
	helpUsersGive = true,
	helpUsersSGive = true,

	helpLinks = true,

	-- server
	serverInfoTitle = true,
	serverInfo = true,

	limitConfirm = true,
	roleConfirm = true,
	roleConfirmNoRoles = true,

	-- lobbies
	lobbiesInfoTitle = true,
	lobbiesNoInfo = true,
	lobbiesInfo = true,
	lobbiesField = true,

	addConfirm = true,
	removeConfirm = true,
	capacityConfirm = true,
	capacityReset = true,
	bitrateOOB = true,
	bitrateOOB1 = true,
	bitrateOOB2 = true,
	bitrateOOB3 = true,
	bitrateConfirm = true,
	categoryConfirm = true,
	categoryReset = true,
	companionEnable = true,
	companionDisable = true,
	nameConfirm = true,
	permissionsConfirm = true,
	permissionsReset = true,
	positionConfirm = true,

	-- matchmaking
	matchmakingInfoTitle = true,
	matchmakingNoInfo = true,
	matchmakingField = true,

	matchmakingAddConfirm = true,
	matchmakingRemoveConfirm = true,
	targetConfirm = true,
	targetReset = true,
	modeConfirm = true,

	-- companion
	companionsInfoTitle = true,
	companionsNoInfo = true,
	companionsField = true,

	greetingConfirm = true,
	greetingReset = true,
	greetingModalTitle = true,
	greetingModalLabel = true,
	roomCommands = true,
	logConfirm = true,
	logReset = true,
	logName = true,
	loggerWarning = true,

	-- room
	roomInfoTitle = true,
	roomInfoHost = true,
	roomInfoVisible = true,
	roomInfoVisibleExceptions = true,
	roomInfoInvisible = true,
	roomInfoInvisibleExceptions = true,
	roomInfoPublic = true,
	roomInfoPublicExceptions = true,
	roomInfoPrivate = true,
	roomInfoPrivateExceptions = true,
	roomInfoVocal = true,
	roomInfoVocalExceptions = true,
	roomInfoSilent = true,
	roomInfoSilentExceptions = true,
	roomInfoWriting = true,
	roomInfoWritingExceptions = true,
	roomInfoMuted = true,
	roomInfoMutedExceptions = true,
	chatInfoVisible = true,
	chatInfoVisibleExceptions = true,
	chatInfoInvisible = true,
	chatInfoInvisibleExceptions = true,
	chatInfoWriting = true,
	chatInfoMuted = true,
	roomInfoCommands = true,
	notInRoom = true,
	none = true,
	muteConfirm = true,
	muteAllConfirm = true,
	unmuteConfirm = true,
	unmuteAllConfirm = true,
	hideConfirm = true,
	hideAllConfirm = true,
	hideNoCompanion = true,
	showConfirm = true,
	showAllConfirm = true,
	showNoCompanion = true,
	kickConfirm = true,
	kickNotInRoom = true,
	blockConfirm = true,
	allowConfirm = true,
	invisibleConfirm = true,
	lockConfirm = true,
	unlockConfirm = true,
	inviteConfirm = true,
	inviteText = true,
	inviteCreated = true,
	noDMs = true,
	hostConfirm = true,
	badNewHost = true,
	hostIdentify = true,
	badHost = true,
	passwordConfirm = true,
	passwordReset = true,
	passwordCheckText = true,
	passwordEnter = true,
	password = true,
	passwordNoChannel = true,
	passwordSuccess = true,
	passwordFailure = true,
	passwordBanned = true,
	noCompanion = true,
	clearConfirm = true,
	renameConfirm = true,
	nameRatelimitRemaining = true,
	nameRatelimitReached = true,

	notHost = true,
	badHostPermission = true,
	renameError = true,
	resizeError = true,
	bitrateError = true,
	inviteError = true,

	-- create
	createCategoryOverflow = true,
	createConfirm = true,

	-- delete
	deleteForm = true,
	deleteNotArmed = true,
	deleteNone = true,
	deleteProcessing = true,
	deleteConfirm = true,

	-- users
	noChildChannels = true,
	usersSent = true,
	usersRolesAdded = true,
	usersRolesRemoved = true,

	-- utility
	embedOK = true,
	embedWarning = true,
	embedError = true,
	asIs = true,

	inCategory = true,

	ping = true,

	-- errors
	notLobby = true,
	lobbyDupe = true,
	channelDupe = true,
	botPermissionsAdmin = true,
	botPermissionsMandatory = true,
	botPermissionsOptional = true,
	botPermissionsOk = true,
	badUserPermissions = true,
	hostMigrationFail = true,
	noParent = true,
	shame = true,
	interactionTimeout = true,
	notInGuild = true,
	wait = true,
	veryNotPermitted = true,

	error = true,
}

return text