return {
	INLINE_PREVIEW_BYTES = 256 * 1024,
	DEFAULT_UPLOAD_BUDGET = 7 * 1024 * 1024,
	TRANSCRIPTS_DIR = "./transcripts",
	imageExtensions = {
		png = true,
		jpg = true,
		jpeg = true,
		gif = true,
		webp = true,
		bmp = true,
		svg = true,
	},
	mimeByExtension = {
		png = "image/png",
		jpg = "image/jpeg",
		jpeg = "image/jpeg",
		gif = "image/gif",
		webp = "image/webp",
		bmp = "image/bmp",
		svg = "image/svg+xml",
		avif = "image/avif",
		mp4 = "video/mp4",
		mov = "video/quicktime",
		webm = "video/webm",
		mp3 = "audio/mpeg",
		wav = "audio/wav",
		ogg = "audio/ogg",
		json = "application/json",
		txt = "text/plain; charset=utf-8",
		pdf = "application/pdf",
		zip = "application/zip",
	},
}